numpy is the library used for numerical calculations and handling arrays

In [1]:
import numpy as np

In this exercise we'll try to build a Linear Regression (LR) model that predicts the cost of our stationary purchase according to a simple formula.

So, imagine that you want to buy a pen and some refills for it, the body costs 10 Rupees and refill costs 5 Rupees each, you have to buy only 1 body and you can choose the number of refills. Therefore the formula of cost becomes : cost = 5(no of refills) + 10, i.e. our LR model has to learn the values of weight as 5 and bias as 10, as y = (weight * x) + bias.

How would you create a LR model that learns this relationship so that it would predict a 7 refills costing close to 45.

In [2]:
lst = [i for i in range(1,10)]
X_train = np.array(lst)
y_train = X_train * 5 + 10
print(X_train)
print(y_train)

[1 2 3 4 5 6 7 8 9]
[15 20 25 30 35 40 45 50 55]


In [3]:
class linear_reg:
    def __init__(self, X_train, y_train, epoch, lr):
        
        self.X_train = X_train
        self.y_train = y_train
        self.epoch = epoch
        self.lr = lr
        self.m = 0
        self.b = 0
        self.predictions = np.array([])
        self.error = np.array([])
        self.len = len(y_train)
    
    def for_prop(self):
        self.predictions = self.X_train*self.m + self.b
    
    def rmse(self):
        self.error = np.sqrt(np.mean(np.square(self.y_train - self.predictions)))
        
    def back_prop(self):
        self.b -= self.lr*np.sum((self.predictions - self.y_train)) / (self.len * np.sqrt(self.error))
        self.m -= self.lr*np.sum((self.predictions - self.y_train) * self.X_train) / (self.len * np.sqrt(self.error))
        
    def run(self):
        for i in range(self.epoch):
            self.for_prop()
            self.rmse()
            self.back_prop()
            print("Epoch =", i, " Error =", self.error)
        
    def predict(self, X_test):
        
        pred = X_test*self.m + self.b
        return pred
        

In [4]:
model = linear_reg(X_train, y_train, 2000, 0.009)

In [5]:
model.run()

Epoch = 0  Error = 37.30504880933232
Epoch = 1  Error = 35.54280883078556
Epoch = 2  Error = 33.82489286825862
Epoch = 3  Error = 32.151428568224745
Epoch = 4  Error = 30.522558824222063
Epoch = 5  Error = 28.93844401844992
Epoch = 6  Error = 27.39926463490729
Epoch = 7  Error = 25.905224307261758
Epoch = 8  Error = 24.456553373338195
Epoch = 9  Error = 23.053513016315655
Epoch = 10  Error = 21.696400078983473
Epoch = 11  Error = 20.385552639240665
Epoch = 12  Error = 19.1213564282478
Epoch = 13  Error = 17.904252150430302
Epoch = 14  Error = 16.734743715978016
Epoch = 15  Error = 15.613407304540926
Epoch = 16  Error = 14.540901017498262
Epoch = 17  Error = 13.517974607103163
Epoch = 18  Error = 12.545478339769831
Epoch = 19  Error = 11.624369386296676
Epoch = 20  Error = 10.75571315046911
Epoch = 21  Error = 9.940675575605285
Epoch = 22  Error = 9.18050069757014
Epoch = 23  Error = 8.476465711934564
Epoch = 24  Error = 7.829804130562417
Epoch = 25  Error = 7.241587373367251
Epoch = 26

In [16]:
pred = model.predict(X_train)
print('\nPredicted values :\n', pred)
print('\n Actual values :\n', y_train)
print('\n Difference between precited and actual values :\n', pred - y_train)


Predicted values :
 [14.93131433 19.94429285 24.95727137 29.97024988 34.9832284  39.99620691
 45.00918543 50.02216395 55.03514246]

 Actual values :
 [15 20 25 30 35 40 45 50 55]

 Difference between precited and actual values :
 [-0.06868567 -0.05570715 -0.04272863 -0.02975012 -0.0167716  -0.00379309
  0.00918543  0.02216395  0.03514246]


In [27]:
print('weight :', model.m, 'bias :', model.b)

weight : 5.012978516135698 bias : 9.91833581796853


We can see that the weight learned is close to 5 and the bias learned is close to 10.

Thus we have created our LR model the hard way from scratch.