numpy is the library used for numerical calculations and handling arrays

In [9]:
import numpy as np

In this exercise we'll try to build a Logistic Regression (LoR) model that predicts whether a number is greater than 4 or not.

For this purpose we will perform a usual Linear Regression and add a sigmoid function in the end to convert the predcitions in range of [0, 1] inclusive. 

In [2]:
lst = [i for i in range(0,10)]
X_train = np.array(lst)
y_train = (X_train > 4) * 1
print(X_train)
print(y_train)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1]


In [3]:
class linear_reg:
    def __init__(self, X_train, y_train, epoch, lr):
        
        self.x = X_train
        self.y = y_train
        self.epoch = epoch
        self.lr = lr
        self.m = 0
        self.b = 0
        self.pred = np.array([])
        self.error = np.array([])
        self.len = len(y_train)
        self.z = np.array([])
        self.db = 0
        self.eps = 1e-8
    
    def sigmoid(self, z):
        y = 1/(1 + np.exp(-z))
        return y
    
    def for_prop(self):
        self.z = self.x*self.m + self.b
        self.pred = self.sigmoid(self.z)
    
    def rmse(self):
        self.error = -(np.sum((self.y * np.log(self.pred + self.eps)) + ((1- self.y) * np.log((1 - self.pred + self.eps)))))
        
    def back_prop(self):
        self.b -= np.sum((((1-self.y)/(1 - self.pred + self.eps)) - (self.y/self.pred + self.eps)) * np.power(self.pred, 2) * np.exp(-self.z))/ self.len
        self.m -= np.sum((((1-self.y)/(1 - self.pred + self.eps)) - (self.y/self.pred + self.eps)) * np.power(self.pred, 2) * np.exp(-self.z) * self.x)/ self.len
        print(self.db)
        
    def run(self):
        for i in range(self.epoch):
            self.for_prop()
            self.rmse()
            self.back_prop()
            print("Epoch =", i, " Error =", self.error)
        
    def predict(self, X_test):
        
        pred = self.sigmoid(X_test*self.m + self.b)
        return pred
        

In [4]:
model = linear_reg(X_train, y_train, 2000, 0.009)

In [5]:
model.run()

0
Epoch = 0  Error = 6.931471605599454
0
Epoch = 1  Error = 13.556623245995002
0
Epoch = 2  Error = 4.9652586052418295
0
Epoch = 3  Error = 4.815089580465554
0
Epoch = 4  Error = 5.771072068197463
0
Epoch = 5  Error = 8.623360888168385
0
Epoch = 6  Error = 21.39895116175604
0
Epoch = 7  Error = 10.453352087862116
0
Epoch = 8  Error = 3.404387916659764
0
Epoch = 9  Error = 3.3259255622572983
0
Epoch = 10  Error = 3.454239734378897
0
Epoch = 11  Error = 4.214747361353503
0
Epoch = 12  Error = 8.772784459172161
0
Epoch = 13  Error = 2.8260179528749365
0
Epoch = 14  Error = 2.7559023243333947
0
Epoch = 15  Error = 2.6908959544959714
0
Epoch = 16  Error = 2.630968217903384
0
Epoch = 17  Error = 2.577429643945523
0
Epoch = 18  Error = 2.5367298858189042
0
Epoch = 19  Error = 2.52553400594566
0
Epoch = 20  Error = 2.6323746755793063
0
Epoch = 21  Error = 2.844433708481942
0
Epoch = 22  Error = 4.138620138902828
0
Epoch = 23  Error = 2.977771855323484
0
Epoch = 24  Error = 4.811826756487041
0


In [6]:
pred = model.predict(X_train)
print('\nPredicted values :\n', pred)
print('\n Actual values :\n', y_train)


Predicted values :
 [4.57856793e-08 2.01406682e-06 8.85893149e-05 3.88217937e-03
 1.46349158e-01 8.82923900e-01 9.96994666e-01 9.99931479e-01
 9.99998442e-01 9.99999965e-01]

 Actual values :
 [0 0 0 0 0 1 1 1 1 1]


In [7]:
print('Converting predictions into 1s and 0s')
pred = (pred >= 0.5) * 1
print('\nPredicted values :\n', pred)
print('\n Difference between precited and actual values :\n', pred - y_train)

Converting predictions into 1s and 0s

Predicted values :
 [0 0 0 0 0 1 1 1 1 1]

 Difference between precited and actual values :
 [0 0 0 0 0 0 0 0 0 0]


In [8]:
print('weight :', model.m, 'bias :', model.b)

weight : 3.783941857475977 bias : -16.899294428861747


We can see that the weight and bias learned.

Predicted values are exactly same as y_train, this is because aur data is very simple and we have used the train data even for testing. It may happen that the accuracy may decrease when we train over a complex data and use different test set. The aim of this demonstration was only to understand Logistic Regression. 

Thus we have created our LoR model the hard way from scratch.